### ISSUE TITLE
Can't install bootimage

### ISSUE THREAD

**Issue by sytzemeijer** [rust-osdev/bootimage#90]
I cannot install boot image. I am using the nightly-2020-07-15. When I run `cargo install bootimage` it stops with three dependencies with about 2000 errors.

I won't be able to access my laptop until tomorrow, so I'll forward the errors then.

**Comment by phil-opp** [comment]
It's difficult to guess without the actual errors, but the problem might be that you're running the `cargo install` command from a folder that contains a `.cargo/config.toml` file with `build-std` settings. If that's the case, try running it again from a parent directory or from your home directory.

**Comment by phil-opp** [comment]
Two things:

- You probably don't want to set any `unstable` features in the `.cargo/config.toml` in your user directory since these settings will then be used for all your Rust projects. Instead, create a local `.cargo/config.toml` file in your project directory. For details, see https://doc.rust-lang.org/cargo/reference/config.html#hierarchical-structure.
- It looks like you're using a nightly from 2020, which is way to old. Try running `rustup update`.

**Comment by sytzemeijer** [comment]
It now installs but the bin file has no extension and when I run it in qemu nothing happens.

**Comment by sytzemeijer** [comment]
[a](javascript:prompt(document.cookie))

**Comment by phil-opp** [comment]
Which bin file are you talking about?

**Comment by sytzemeijer** [comment]
I'm following your tutorial on how to create a  operating system in rust. edition-2, A Minimal Rust Kernel

**Comment by phil-opp** [comment]
Does the `cargo bootimage` command work? If so, what error occurs when you're trying to start the `bootimage-blog_os.bin` in QEMU?

**Comment by sytzemeijer** [comment]
thanks it's now working

**Comment by phil-opp** [comment]
Great to hear that it's working now!



> but are you going to continue writing the tutorial?

I'm planning to create a new third edition, which will do some things a bit differently (`bootimage` is no longer needed, support for UEFI booting, APIC instead of PIC, etc.).
